---
title: "R Notebook"
output: html_notebook
---

```{r}
library(tidyverse)
library(pryr)
```

Following along through the expressions 
http://adv-r.had.co.nz/Expressions.html
```{r}
z <- quote(y <- x * 10) # quote returns an expression
z # an expression
ast(y <- x * 10)
```

formals()
```{r}
f <- function(x) a + b
formals(f) <- alist(a = , b = 3)
f    # function(a, b = 3) a + b
f(2) # result = 5


# You can use formals() to both get and set the arguments of a function. Use formals() to modify the following function so that the default value of x is missing and y is 10.
g <- function(x = 20, y) {
  x + y
}

formals(g) <- alist(x = , y = 10)

g(1)

### NOTE! formals probably can and should be used for the savistky golay filtering stuff!!
# e.g. 
# formats(sgolay <- alist(n_ = 13, window = 5))
```

Calls
```{r}
y <- quote(add(10)(20))
y[[1]]
#> add(10)
is.call(y[[1]])
#> [1] TRUE

y[[2]]
# [1] 20
is.call(y[[2]])
# [1] FALSE
```
To work around this problem, pryr provides standardise_call(). It uses the base match.call() function to convert all positional arguments to named arguments:
```{r}
m1 <- quote(read.delim("data.txt", sep = "|"))
m2 <- quote(read.delim(s = "|", "data.txt"))
m3 <- quote(read.delim(file = "data.txt", , "|"))

standardise_call(m1)
#> read.delim(file = "data.txt", sep = "|")
standardise_call(m2)
#> read.delim(file = "data.txt", sep = "|")
standardise_call(m3)
#> read.delim(file = "data.txt", sep = "|")

```

Capturing the current call
```{r}
f <- function(abc = 1, def = 2, ghi = 3) {
  list(sys = sys.call(), match = match.call())
}

f(d = 2, 2)

mod <- lm(mpg ~ wt, data = mtcars)
update(mod, formula = . ~ . + cyl)
```

```{r}
z <- rlang::expr(y <- x*10)
z
#  y <- x * 10
x <- 4
eval(z) # woah, wrote y without a visible assignment. I don't love this...?
y
# [1] 40
```

```{r}
library(rlang)
library(lobstr)
```

https://win-vector.com/2018/09/01/r-tip-how-to-pass-a-formula-to-lm/
```{r}
outcome <- "mpg"
variables <- c("cyl", "disp", "hp", "carb")

f <- as.formula(
  paste(outcome, 
        paste(variables, collapse = " + "), 
        sep = " ~ "))
print(f)
# mpg ~ cyl + disp + hp + carb


# The new line of code
model <- eval(bquote(   lm(.(f), data = mtcars)   ))

print(model)
# Call:
#   lm(formula = mpg ~ cyl + disp + hp + carb, data = mtcars)
# 
# Coefficients:
#   (Intercept)          cyl         disp           hp         carb  
#     34.021595    -1.048523    -0.026906     0.00
```